# -*- coding: utf-8 -*-
"""Graph_ML_H1_Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fY36YIeVaZjYUskIOWqFoEbTj92MRur6

# Graph Machine Learning

## Introduction

Graph Machine Learning has become an important approach for analyzing relational data.  
In this study, a graph-based email classification pipeline is implemented where each email is represented as a node and connections are created based on text similarity.

Several graph representation learning methods, including **DeepWalk**, **Node2Vec**, **SiGraC-based embeddings with different proximity measures**, and a **Graph Convolutional Network (GCN)**, are applied and compared in terms of classification performance.
"""

#pip install pandas numpy scikit-learn networkx gensim node2vec spacy torch torch-geometric matplotlib
#python -m spacy download en_core_web_sm

import pandas as pd
import numpy as np
import networkx as nx
import random
import time
import re

import matplotlib.pyplot as plt

from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score

from gensim.models import Word2Vec
from node2vec import Node2Vec

import torch
import torch.nn.functional as F
from torch_geometric.data import Data
from torch_geometric.nn import GCNConv

data = fetch_20newsgroups(remove=('headers','footers','quotes'))

texts = data.data

print("Toplam text sayısı:", len(texts))

texts[:3]

sample_size = 1000

texts = random.sample(texts, sample_size)

print("Yeni veri sayısı:", len(texts))

vectorizer = CountVectorizer(
    stop_words="english",
    max_features=1000
)

bow_matrix = vectorizer.fit_transform(texts)

print("BoW matrix boyutu:", bow_matrix.shape)

feature_names = vectorizer.get_feature_names_out()
print("İlk 20 kelime:", feature_names[:20])

labels = []

for text in texts:
    if len(text) > 500:
        labels.append(1)
    else:
        labels.append(0)

print("Toplam label sayısı:", len(labels))
print("İlk 10 label:", labels[:10])

similarity_matrix = cosine_similarity(bow_matrix)

print("Similarity matrix boyutu:", similarity_matrix.shape)

G = nx.Graph()

for i in range(len(texts)):
    G.add_node(i)

threshold = 0.3

for i in range(len(texts)):
    for j in range(i + 1, len(texts)):
        if similarity_matrix[i][j] > threshold:
            G.add_edge(i, j)

print("Node sayısı:", G.number_of_nodes())
print("Edge sayısı:", G.number_of_edges())

degrees = [deg for _, deg in G.degree()]
print("Ortalama degree:", sum(degrees) / len(degrees))

def random_walk(graph, start, walk_length):
    walk = [start]

    for _ in range(walk_length - 1):
        neighbors = list(graph.neighbors(walk[-1]))

        if len(neighbors) == 0:
            break

        next_node = random.choice(neighbors)
        walk.append(next_node)

    return walk

walks = []

num_walks = 10
walk_length = 10

for node in G.nodes():
    for _ in range(num_walks):
        walk = random_walk(G, node, walk_length)
        walks.append([str(n) for n in walk])

print("Toplam walk sayısı:", len(walks))
print("İlk 3 walk:", walks[:3])

start = time.time()

model_dw = Word2Vec(
    sentences=walks,
    vector_size=64,
    window=5,
    min_count=0,
    sg=1,
    workers=4
)

deepwalk_time = time.time() - start

print("DeepWalk training time:", deepwalk_time)

deepwalk_embeddings = []

for node in G.nodes():
    deepwalk_embeddings.append(model_dw.wv[str(node)])

deepwalk_embeddings = np.array(deepwalk_embeddings)

print("DeepWalk embedding boyutu:", deepwalk_embeddings.shape)

X_train, X_test, y_train, y_test = train_test_split(
    deepwalk_embeddings,
    labels,
    test_size=0.2,
    random_state=42
)

clf_dw = LogisticRegression(max_iter=1000)
clf_dw.fit(X_train, y_train)

pred_dw = clf_dw.predict(X_test)

deepwalk_acc = accuracy_score(y_test, pred_dw)
deepwalk_f1 = f1_score(y_test, pred_dw)

print("DeepWalk Accuracy:", deepwalk_acc)
print("DeepWalk F1 Score:", deepwalk_f1)

node2vec_model = Node2Vec(
    G,
    dimensions=64,
    walk_length=10,
    num_walks=10,
    workers=4
)

start = time.time()

model_n2v = node2vec_model.fit(
    window=5,
    min_count=1
)

node2vec_time = time.time() - start

print("Node2Vec training time:", node2vec_time)

node2vec_embeddings = []

for node in G.nodes():
    node2vec_embeddings.append(model_n2v.wv[str(node)])

node2vec_embeddings = np.array(node2vec_embeddings)

print("Node2Vec embedding boyutu:", node2vec_embeddings.shape)

X_train, X_test, y_train, y_test = train_test_split(
    node2vec_embeddings,
    labels,
    test_size=0.2,
    random_state=42
)

clf_n2v = LogisticRegression(max_iter=1000)
clf_n2v.fit(X_train, y_train)

pred_n2v = clf_n2v.predict(X_test)

node2vec_acc = accuracy_score(y_test, pred_n2v)
node2vec_f1 = f1_score(y_test, pred_n2v)

print("Node2Vec Accuracy:", node2vec_acc)
print("Node2Vec F1 Score:", node2vec_f1)

A = nx.to_numpy_array(G)
degrees = A.sum(axis=1)

n = A.shape[0]
common_neighbors = A @ A

print("Adjacency shape:", A.shape)
print("Common neighbors shape:", common_neighbors.shape)

def safe_divide(num, denom):
    out = np.zeros_like(num, dtype=float)
    mask = denom != 0
    out[mask] = num[mask] / denom[mask]
    return out

deg_i = degrees.reshape(-1, 1)
deg_j = degrees.reshape(1, -1)

min_deg = np.minimum(deg_i, deg_j)

HPI = safe_divide(common_neighbors, min_deg)

print("HPI matrix shape:", HPI.shape)

from sklearn.decomposition import TruncatedSVD

def get_embedding_from_matrix(M, dim=64):
    svd = TruncatedSVD(n_components=dim, random_state=42)
    emb = svd.fit_transform(M)
    return emb

start = time.time()

emb_hpi = get_embedding_from_matrix(HPI, dim=64)

sig_hpi_time = time.time() - start

print("SiGraC-HPI embedding shape:", emb_hpi.shape)
print("SiGraC-HPI time:", sig_hpi_time)

X_train, X_test, y_train, y_test = train_test_split(
    emb_hpi,
    labels,
    test_size=0.2,
    random_state=42
)

clf_hpi = LogisticRegression(max_iter=1000)
clf_hpi.fit(X_train, y_train)

pred_hpi = clf_hpi.predict(X_test)

hpi_acc = accuracy_score(y_test, pred_hpi)
hpi_f1 = f1_score(y_test, pred_hpi)

print("SiGraC-HPI Accuracy:", hpi_acc)
print("SiGraC-HPI F1:", hpi_f1)

max_deg = np.maximum(deg_i, deg_j)

HDI = safe_divide(common_neighbors, max_deg)

print("HDI matrix shape:", HDI.shape)

start = time.time()

emb_hdi = get_embedding_from_matrix(HDI, dim=64)

sig_hdi_time = time.time() - start

print("SiGraC-HDI embedding shape:", emb_hdi.shape)
print("SiGraC-HDI time:", sig_hdi_time)

X_train, X_test, y_train, y_test = train_test_split(
    emb_hdi,
    labels,
    test_size=0.2,
    random_state=42
)

clf_hdi = LogisticRegression(max_iter=1000)
clf_hdi.fit(X_train, y_train)

pred_hdi = clf_hdi.predict(X_test)

hdi_acc = accuracy_score(y_test, pred_hdi)
hdi_f1 = f1_score(y_test, pred_hdi)

print("SiGraC-HDI Accuracy:", hdi_acc)
print("SiGraC-HDI F1:", hdi_f1)

AA = np.zeros((n, n), dtype=float)

for z in range(n):
    if degrees[z] > 1:
        weight = 1.0 / np.log(degrees[z])
        neighbors = np.where(A[z] > 0)[0]
        for i in neighbors:
            for j in neighbors:
                if i != j:
                    AA[i, j] += weight

print("AA matrix shape:", AA.shape)

start = time.time()

emb_aa = get_embedding_from_matrix(AA, dim=64)

sig_aa_time = time.time() - start

print("SiGraC-AA embedding shape:", emb_aa.shape)
print("SiGraC-AA time:", sig_aa_time)

X_train, X_test, y_train, y_test = train_test_split(
    emb_aa,
    labels,
    test_size=0.2,
    random_state=42
)

clf_aa = LogisticRegression(max_iter=1000)
clf_aa.fit(X_train, y_train)

pred_aa = clf_aa.predict(X_test)

aa_acc = accuracy_score(y_test, pred_aa)
aa_f1 = f1_score(y_test, pred_aa)

print("SiGraC-AA Accuracy:", aa_acc)
print("SiGraC-AA F1:", aa_f1)

x = torch.tensor(bow_matrix.toarray(), dtype=torch.float)
y = torch.tensor(labels, dtype=torch.long)

print("x shape:", x.shape)
print("y shape:", y.shape)

edge_index = []

for edge in G.edges():
    edge_index.append([edge[0], edge[1]])
    edge_index.append([edge[1], edge[0]])

edge_index = torch.tensor(edge_index, dtype=torch.long).t().contiguous()

print("edge_index shape:", edge_index.shape)

data = Data(x=x, edge_index=edge_index, y=y)

print(data)

class GCN(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = GCNConv(1000, 64)
        self.conv2 = GCNConv(64, 2)

    def forward(self, data):
        x, edge_index = data.x, data.edge_index

        x = self.conv1(x, edge_index)
        x = torch.relu(x)
        x = self.conv2(x, edge_index)

        return x

model = GCN()

optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
criterion = torch.nn.CrossEntropyLoss()

start = time.time()

for epoch in range(100):
    model.train()

    optimizer.zero_grad()

    out = model(data)

    loss = criterion(out, data.y)

    loss.backward()
    optimizer.step()

    if epoch % 10 == 0:
        print("Epoch:", epoch, "Loss:", loss.item())

gcn_time = time.time() - start

print("GCN training time:", gcn_time)

model.eval()

pred_gcn = model(data).argmax(dim=1)

correct = (pred_gcn == data.y).sum()
gcn_acc = int(correct) / len(labels)

print("GCN Accuracy:", gcn_acc)

"""## Results

| Method | Accuracy | F1 | Time to Train (s) |
|------|------|------|------|
| DeepWalk | 0.575 | 0.560 | 1.75 |
| Node2Vec | 0.605 | 0.559 | 2.31 |
| SiGraC-HPI | 0.680 | 0.736 | 0.48 |
| SiGraC-HDI | 0.665 | 0.720 | 0.30 |
| SiGraC-AA | 0.650 | 0.715 | 0.50 |
| GCN | **0.948** | - | 2.99 |

## Performance Analysis

Among the evaluated methods, **GCN achieved the best performance with an accuracy of 0.948**.

Graph embedding methods such as **DeepWalk** and **Node2Vec** produced moderate performance since they only learn representations based on graph structure.

The **SiGraC-based proximity embeddings (HPI, HDI, and AA)** improved the results by incorporating neighborhood similarity information between nodes.

However, **Graph Convolutional Networks outperform the other methods** because they jointly utilize both **node features (Bag-of-Words representations)** and **graph topology**, allowing the model to learn richer node representations.
"""

plt.figure(figsize=(8,6))

pos = nx.spring_layout(G, seed=42)

nx.draw(
    G,
    pos,
    node_size=20,
    edge_color="gray",
    alpha=0.6,
    with_labels=False
)

plt.title("Email Graph Visualization")
plt.show()